### ISSUE TITLE
sh2 中的问题

### ISSUE THREAD

**Issue by Triple-Z** [FlyAndNotDown/os-tasks#1]
https://github.com/FlyAndNotDown/os-tasks/blob/f970d3d12a01a2e88cb6f65d364897af3e8ca163/2-multi-process/3-sh2/sh2.c#L64

直接借助 `shell` 执行重定向？没有使用 `dup2` 进行重定向操作嘛……

**Comment by FlyAndNotDown** [comment]
我还没写，马上考人工智能，考完人工智能再写🍭

**Comment by FlyAndNotDown** [comment]
sh2和sh3都还没写
